[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Vitalinux Radiance
Comment=Green variation of Ubuntu Radiance theme & metacity Equinox Theme for Vitalinux
Comment[es]=Variante en tonos verdes del tema Ubuntu Radiance y Equinox para Vitalinux
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Vitalinux Radiance
MetacityTheme=Vitalinux Radiance
IconTheme=vitalinux
CursorTheme=DMZ-white
ButtonLayout=menu:minimize,maximize,spacer,close
